In [4]:
import numpy as np
array1 = [10, 20, 30]

print(array1)

[10, 20, 30]


In [5]:
np.array(array1)

array([10, 20, 30])

In [6]:
array2 = [10, 20, 'xyz']
np.array(array2)

array(['10', '20', 'xyz'], dtype='<U11')

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
x1 = np.ones(5)
print(x1)

[1. 1. 1. 1. 1.]


In [11]:
x1[2]='xyz'

ValueError: could not convert string to float: 'xyz'

In [14]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
x.dtype

dtype('float64')

In [16]:
x = np.zeros(10, int)
print(x)
y = x.dtype
print(y)

[0 0 0 0 0 0 0 0 0 0]
int32


In [17]:
x1 = np.ones(1)
print(x1)

[1.]


In [18]:
x1 = np.ones(15)

x1[2] = 2
print(x1)

[1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
x1 = np.ones(15)

x1[2] = "2"
print(x1)

[1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
x1 = np.ones(15)

x1[2] = "as"
print(x1)

ValueError: could not convert string to float: 'as'

In [21]:
np.zeros(3, 4)

TypeError: Cannot interpret '4' as a data type

In [22]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
new_array = np.zeros((3, 4, 5))
print(new_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [26]:
new_array[0][1][2]

0.0

In [27]:
new_array[0][1]

array([0., 0., 0., 0., 0.])

In [28]:
new_array[0]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
new_array.shape

(3, 4, 5)

In [30]:
a = np.zeros(5)
print(a)
a[2:5]

[0. 0. 0. 0. 0.]


array([0., 0., 0.])

In [32]:
twoD_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twoD_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(twoD_array[2])

[7 8 9]


In [34]:
twoD_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
twoD_array[1:3, 0]


array([4, 7])

In [35]:
twoD_array[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [36]:
x = [1, 2, 3]
y = [4, 5, 6]
x = x + 10
print(x)


TypeError: can only concatenate list (not "int") to list

In [37]:
print(x+y)

[1, 2, 3, 4, 5, 6]


In [38]:
import numpy as np
import math as m

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x = x + 10
print(x)

[11 12 13]


In [39]:
print(x+y)

[15 17 19]


In [40]:
z = np.array([7, 8, 9, 10])
print(x+z) #This gave an error because the dimensions of x and y are unequal.

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [41]:
print(x*2)

[22 24 26]


In [42]:
print(x*y)

[44 60 78]


In [43]:
print(x**2)

[121 144 169]


In [44]:
print(x.mean())

12.0


In [45]:
print(x.sum())

36


In [46]:
p1 = np.array([1, 1, 1])
p2 = np.array([2, 2, 2])

val = ((p1-p2)**2)
print(val)

[1 1 1]


In [47]:
p1 = np.array([1, 1, 1])
p2 = np.array([2, 2, 2])

val = ((p1-p2)**2).sum()
print(val)

m.sqrt(val) #Heron's Formula

3


1.7320508075688772

In [48]:
p1 = np.array([1, 1, 1])
p2 = np.array([2, 2, 2])

val = ((p1-p2)**2)
print(val)

val2 = val.sum()
print(val2)

[1 1 1]
3


In [49]:
pts = np.array([4, 5, 6, 7])

val1 = ((pts - pts.mean())**2).sum()
print(val1)
m.sqrt(val1)

5.0


2.23606797749979

In [50]:
m1 = np.array([1, 2, 3])
m2 = np.array([4, 5, 6])

print(m1.dot(m2))
print(m2.dot(m1))

32
32
