In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Multiple Linear Regression can be defined as the regression which is dependent on more than one independent variables. Equation for Multiple Linear Regression can be written as 
#y = ax1 + ax2 + ax3 + ax4 + ..... + axn + c where y is a dependent variable, a is a constant, just like in the equation of the straight line y = mx + c, m is a slope and constant and all the variants of x are the independent variables on which y depends. 
